/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.CategoriaDAO;
import DAO.ClienteDAO;
import DAO.EntradaDAO;
import Modelo.Cliente;
import Modelo.Entrada;
import Modelo.Iva;
import Modelo.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class formRegistroEntradasEdit extends javax.swing.JFrame {

    Usuario sysUser;
    String identra;
    /**
     * Creates new form formUsuarioAdd
     */
    public formRegistroEntradasEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public formRegistroEntradasEdit(String id, Usuario user) {
        initComponents();
        this.sysUser = user;
        this.identra = id;
        this.setLocationRelativeTo(null);
        this.getPorcentaje();
        this.getDatosProducto();
    }
    
    
    public void getDatosProducto(){
        
        Entrada entra = new Entrada();
        EntradaDAO entraDAO = new EntradaDAO();
        
        System.out.println(identra);
        entra = entraDAO.leer(Integer.parseInt(identra));
        
        txtCodigo.setText(entra.getCodigo());
        txtIdProve.setText(entra.getIdProveedor());
        txtSubTotal.setText(String.valueOf(entra.getSubtotal()));
        txtTotal.setText(String.valueOf(entra.getTotal()));

    }
    
    
   /* public void getCategorias(){
        CategoriaDAO cateDAO = new CategoriaDAO();
        List<Categoria> categorias = cateDAO.listar();

        listCategoria.removeAllItems();
        for(Categoria cat:categorias){
            listCategoria.addItem(new Categoria(cat.getIdCategoria(),cat.getNombre()));
        }
        
    }*/
    
    
   /* public void getMedidas(){
        MedidaDAO mediDAO = new MedidaDAO();
        List<Medida> medidas = mediDAO.listar();

        listMedida.removeAllItems();
        for(Medida med:medidas){
            listMedida.addItem(new Medida(med.getIdMedida(), med.getAbreviatura()));
        }
        
    }*/
    
    
    public void getPorcentaje(){
        
        listIva.removeAllItems();
        listIva.addItem(new Iva("0%",1));
        listIva.addItem(new Iva("12%",2));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labSubTotal = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labfecha = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labIdProve = new javax.swing.JLabel();
        txtIdProve = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        labPrecio = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        labIva = new javax.swing.JLabel();
        labCodigo = new javax.swing.JLabel();
        listIva = new javax.swing.JComboBox<>();
        labTotal = new javax.swing.JLabel();
        txtFecha2 = new javax.swing.JFormattedTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        labSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        labSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        labSubTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Modificar Producto");
        labSubTotal.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labfecha.setText("Fecha");
        labSubTotal.add(labfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        labSubTotal.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        labIdProve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIdProve.setText("ID Provedor");
        labSubTotal.add(labIdProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        txtIdProve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdProve.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIdProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveActionPerformed(evt);
            }
        });
        labSubTotal.add(txtIdProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 200, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Cancelar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        labSubTotal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 90, 30));

        btnGuardar1.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        labSubTotal.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 90, 30));

        labPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPrecio.setText("Sub Total");
        labSubTotal.add(labPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });
        labSubTotal.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, 30));

        labIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIva.setText("Porcentaje IVA");
        labSubTotal.add(labIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        labCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCodigo.setText("Código");
        labSubTotal.add(labCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));
        labSubTotal.add(listIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 190, 30));

        labTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labTotal.setText("Total");
        labSubTotal.add(labTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        txtFecha2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFecha2.setText("dd/MM/yyyy");
        labSubTotal.add(txtFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 30));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        labSubTotal.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        
        Entrada entra = new Entrada();
        EntradaDAO entraDAO = new EntradaDAO();
        
        if(!txtCodigo.getText().equals("") && !txtIdProve.getText().equals("") && 
                !txtSubTotal.getText().equals("") && 
                !txtFecha2.getText().equals("")&& 
                !txtFecha2.getText().equals("dd/MM/yyyy")){
            
           entra.setCodigo((String)txtCodigo.getText());
            entra.setIdProveedor(String.valueOf(txtIdProve.getText()));
            entra.setSubtotal(Float.parseFloat(txtSubTotal.getText()));
            entra.setValorIva((int) listIva.getItemAt(listIva.getSelectedIndex()).getValor());                      
            LocalDate fecha = LocalDate.parse(txtFecha2.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
            entra.setFechaEntrada(fecha);                     
                entra.setEstado(1);
                entra.setFechaModifica(LocalDateTime.now());
                entra.setUsuarioModifica(sysUser.getUsername());
                            
                if(txtCodigo.getText().length() == 5){
                    if(entraDAO.modificar(entra)){                           
                        this.dispose();
                        formProductos.getProductos();

                    }else{
                        JOptionPane.showMessageDialog(null, "No se guardaron los datos.");
                    }
                }else{
                
                    JOptionPane.showMessageDialog(null, "El código no puede superar los 5 dígitos.");
                } 
                        
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos del formulario.");
        }
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistroEntradasEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labIdProve;
    private javax.swing.JLabel labIva;
    private javax.swing.JLabel labPrecio;
    private javax.swing.JPanel labSubTotal;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel labfecha;
    private javax.swing.JComboBox<Iva> listIva;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFecha2;
    private javax.swing.JTextField txtIdProve;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
